services:
  frontend:
    image: espeather-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:5173
    depends_on:
     - backend

  backend:
    image: espeather-backend
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MQTT_CONFIG: ${MQTT_CONFIG}
